mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls'))
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    # ex /polls/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from __future__ import unicode_literals
import datetime
from django.db import models

from django.utils import timezone

class Question(models.Model):
    def __str__(self):
        return self.question_text

    def was_recently_published(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Person(models.Model):
    def __str__(self):
        return self.first_name + ' ' + self.last_name
    first_name = models.CharField(max_length = 200)
    last_name = models.CharField(max_length = 200)
    age = models.IntegerField(default = 0)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import Question

def index(request):
    last_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'last_question_list': last_question_list 
    }
    return HttpResponse(template.render(context, request))    

def detail(request, question_id):
    try: 
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exist')
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    return HttpResponse('You are looking at result %s' % question_id)

def vote(request, question_id):
    return HttpResponse('You are voting on question %s' % question_id)


    

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
  <header id="header">
    Python toy app
  </header>
  <div id="wrap">
    <div id="sidebar">
        <ul>
            {% block sidebar %}
            <li><a href="/">Home</a></li>
            <li><a href="/polls/">Polls</a></li>
            <li><a href="/admin/">Admin</a></li>
            {% endblock %}
        </ul>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
  </div>
  <footer id="footer">
    footer is here.
  </footer>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block title %}
    Detail Page
{% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>
            <a href="{% url 'polls:vote' question.id %}">{{ choice.choice_text }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}
{% block title %}
Index Page
{% endblock%}
{% block sidebar %}
{{ block.super }}
<li><a href="/aboutus">About Us</a></li>
{% endblock %}
{% block content %}
    {% if last_question_list %}
    <ul>
        {% for question in last_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available</p>
    {% endif %}
{% endblock %}